### ISSUE TITLE
Model Paths and Requirements.txt

### ISSUE THREAD

**Issue by ethantenison** [ma-ji/npo_classifier#16]
I had the hardest time getting the model path to work. Upon further investigation into Bert_API.ipynb, I realized you can't change the path from 'npoclass_model_bc/' or else it will throw an error. This will be a problem if your Jupyter notebook and model folder aren't in the same directory. In order to fix it I went into your Jupyter notebook and changed that section. 

Another issue I had was using the requirements.txt file to install packages. I'm on Windows, and I'm thinking you used either Linux or Mac because some of those package distributions did not exist. You might want to specify which operating system you used. 

I don't think the major category model is linked for download either.

**Comment by ma-ji** [comment]
Thanks, Ethan, I'll be working on it! 

Yes, I was using Linux. Will specify that as well.

Happy coding!

**Comment by gtl-alex** [comment]
Hi @ma-ji, thank you for all your work on this project! Quick question, do I have to do anything special to install the dependencies specified in `requirements.txt`? It looks like a commit on 04/10/2021 replaced version numbers with hardcoded paths.

Example:

> attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
Babel @ file:///tmp/build/80754af9/babel_1607110387436/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1617198481742/work

**Comment by ma-ji** [comment]
@gtl-alex Thanks for checking this out!

I think you can ignore these local paths--must be not using correct options when I ran `pip freeze`. I'll check that later.

**Comment by ma-ji** [comment]
The latest update fixed this issue.
